# Generated by Django 4.1.2 on 2022-10-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="band",
            old_name="country",
            new_name="title",
        ),
    ]
